services:
  - type: web
    name: one-piece-character-tracker
    env: python
    buildCommand: pip install -r requirements.txt
    startCommand: python app.py
    envVars:
      - key: FLASK_ENV
        value: production
      - key: HOST
        value: 0.0.0.0
      - key: PORT
        value: 10000
      - key: DATABASE_PATH
        value: one_piece_tracker.db
    disk:
      name: data
      mountPath: /opt/render/project/src/data
      sizeGB: 1